DROP TABLE IF EXISTS 
	award, 						--1
	character, 					--2
	director, 					--3
	rating, 					--4
	studio, 					--5
	genre, 						--6
	keyword, 					--7
	movie, 						--8
	sales,						--9
	liwc_score, 				--10
	expert_review,				--11
	user_review,				--12
	bridge_movie_award,			--13
	bridge_movie_director,		--14
	bridge_movie_genre,			--15
	bridge_movie_character,		--16
	bridge_movie_expert_review,	--17
	bridge_movie_user_review,	--18
	bridge_movie_studio,		--19
	bridge_movie_keyword,		--20
						
CASCADE 
;                  		


-- 1 - create awards tbl
CREATE TABLE award (
    id_award INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 	-- id award is INTEGER, primary key, auto increment
    award_name VARCHAR(255)
);

-- 2 - create character tbl
CREATE TABLE character (
  id_character INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 	-- id character is INTEGER, primary key, auto increment
  character_name VARCHAR(100)
); 


-- 3 - create director tbl
CREATE TABLE director (
  id_director INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  director_name VARCHAR(100)
);

-- 4 - create rating tbl
CREATE TABLE rating (
  id_rating INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rating_code VARCHAR(50),
  rating_name VARCHAR(100) 
); 

-- 5 - create studio tbl
CREATE TABLE studio (
  id_studio INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  studio_name VARCHAR(100) 
);

-- 6 - create genre tbl
CREATE TABLE genre (
  id_genre INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  genre_name VARCHAR(100) 
); 

-- 7 - create keyword tbl
CREATE TABLE keyword (
  id_keyword INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  keyword VARCHAR(100) 
);

-- 8 - create movie tbl
--DROP TABLE IF EXISTS movie CASCADE;
CREATE TABLE movie (
  id_movie INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_rating INTEGER,
  title VARCHAR(255),
  release_date DATE,
  runtime DECIMAL(5,2),
  metascore INTEGER,
  userscore DECIMAL(5,2),
  creative_type VARCHAR(255),
  url VARCHAR(255),

  CONSTRAINT fk_movie_rating					-- create id rating as FK 
  	FOREIGN KEY (id_rating) 
	REFERENCES rating (id_rating)
	
);
CREATE INDEX idx_movie_id_rating					-- Create an index called fk_movie_rating to make searches involving movie.id_rating faster. Without an index,SQL need to check many rows. lookup structure
ON movie (id_rating);

-- 9 - create sales tbl
CREATE TABLE sales (
  id_sales INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_movie INTEGER,
  production_budget DECIMAL(15,2),
  domestic_box_office DECIMAL(15,2),
  international_box_office DECIMAL(15,2),
  worldwide_box_office DECIMAL(15,2),
  opening_weekend DECIMAL(15,2),
  theatre_count INTEGER,
  avg_run_per_theatre DECIMAL(15,2),
  url VARCHAR(255),

  CONSTRAINT fk_sales_movie
        FOREIGN KEY (id_movie)
        REFERENCES movie (id_movie)

);
CREATE INDEX idx_sales_id_movie
ON sales (id_movie);

-- 10 - create liwc_score tbl
CREATE TABLE liwc_score (
  	id_liwc INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  	wc			DECIMAL(10,2),
	analytic	DECIMAL(10,2),
	clout		DECIMAL(10,2),
	authentic	DECIMAL(10,2),
	tone		DECIMAL(10,2),
	wps			DECIMAL(10,2),
	sixltr		DECIMAL(10,2),
	dic			DECIMAL(10,2),
	function	DECIMAL(10,2),
	pronoun		DECIMAL(10,2),
	ppron		DECIMAL(10,2),
	i			DECIMAL(10,2),
	we			DECIMAL(10,2),
	you			DECIMAL(10,2),
	shehe		DECIMAL(10,2),
	they		DECIMAL(10,2),
	ipron		DECIMAL(10,2),
	article		DECIMAL(10,2),
	prep		DECIMAL(10,2),
	auxverb		DECIMAL(10,2),
	adverb		DECIMAL(10,2),
	conj		DECIMAL(10,2),
	negate		DECIMAL(10,2),
	verb		DECIMAL(10,2),
	adj			DECIMAL(10,2),
	compare		DECIMAL(10,2),
	interrog	DECIMAL(10,2),
	number	DECIMAL(10,2),
	quant	DECIMAL(10,2),
	affect	DECIMAL(10,2),
	posemo	DECIMAL(10,2),
	negemo	DECIMAL(10,2),
	anx		DECIMAL(10,2),
	anger	DECIMAL(10,2),
	sad		DECIMAL(10,2),
	social	DECIMAL(10,2),
	family	DECIMAL(10,2),
	friend	DECIMAL(10,2),
	female	DECIMAL(10,2),
	male	DECIMAL(10,2),
	cogproc	DECIMAL(10,2),
	insight	DECIMAL(10,2),
	cause	DECIMAL(10,2),
	discrep	DECIMAL(10,2),
	tentat	DECIMAL(10,2),
	certain	DECIMAL(10,2),
	differ	DECIMAL(10,2),
	percept	DECIMAL(10,2),
	see		DECIMAL(10,2),
	hear	DECIMAL(10,2),
	feel	DECIMAL(10,2),
	bio		DECIMAL(10,2),
	body	DECIMAL(10,2),
	health	DECIMAL(10,2),
	sexual	DECIMAL(10,2),
	ingest	DECIMAL(10,2),
	drives	DECIMAL(10,2),
	affiliation	DECIMAL(10,2),
	achieve	DECIMAL(10,2),
	power	DECIMAL(10,2),
	reward	DECIMAL(10,2),
	risk	DECIMAL(10,2),
	focuspast	DECIMAL(10,2),
	focuspresent	DECIMAL(10,2),
	focusfuture	DECIMAL(10,2),
	relativ	DECIMAL(10,2),
	motion	DECIMAL(10,2),
	space	DECIMAL(10,2),
	time	DECIMAL(10,2),
	work	DECIMAL(10,2),
	leisure	DECIMAL(10,2),
	home	DECIMAL(10,2),
	money	DECIMAL(10,2),
	relig	DECIMAL(10,2),
	death	DECIMAL(10,2),
	informal	DECIMAL(10,2),
	swear	DECIMAL(10,2),
	netspeak	DECIMAL(10,2),
	assent	DECIMAL(10,2),
	nonflu	DECIMAL(10,2),
	filler	DECIMAL(10,2),
	allpunc	DECIMAL(10,2),
	period	DECIMAL(10,2),
	comma	DECIMAL(10,2),
	colon	DECIMAL(10,2),
	semic	DECIMAL(10,2),
	qMark	DECIMAL(10,2),
	exclam	DECIMAL(10,2),
	dash	DECIMAL(10,2),
	quote	DECIMAL(10,2),
	apostro	DECIMAL(10,2),
	parenth	DECIMAL(10,2),
	otherp	DECIMAL(10,2)
);
  

-- 11 - create expert_review tbl
--DROP TABLE IF EXISTS expert_review CASCADE;
CREATE TABLE expert_review (
  id_expert_review INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_liwc INTEGER,
  expert_name VARCHAR,
  review_date DATE,
  idvscore DECIMAL(5,2),
  review_text VARCHAR,
  url VARCHAR,

  CONSTRAINT fk_expert_review_liwc
  	FOREIGN KEY (id_liwc) 
	REFERENCES liwc_score (id_liwc)
); 
CREATE INDEX idx_expert_review_id_liwc			
ON expert_review (id_liwc);


-- 12 - create user_review tbl
--DROP TABLE IF EXISTS user_review CASCADE;
CREATE TABLE user_review (
  id_user_review INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_liwc INTEGER,
  user_name VARCHAR ,
  review_date DATE ,
  idvscore DECIMAL(5,2) ,
  thumbsup DECIMAL(5,2) ,
  thumbstot DECIMAL(5,2) ,
  review_text VARCHAR ,
  url VARCHAR,

  CONSTRAINT fk_user_review_liwc
  	FOREIGN KEY (id_liwc) 
	REFERENCES liwc_score (id_liwc)
); 
CREATE INDEX idx_user_review_id_liwc				
ON user_review (id_liwc);



-- 13 - create bridge_award_movie tbl
CREATE TABLE bridge_movie_award (
  id_movie INTEGER NOT NULL,
  id_award INTEGER NOT NULL,
  
  -- Prevents duplicate movie-award combinations
  PRIMARY KEY (id_movie, id_award),
    
  -- Desalese Foreign Key Constraints with Cascade Delete, preventing orphaned data records.
  CONSTRAINT fk_bridge_movie_award_movie 
        FOREIGN KEY (id_movie) 
        REFERENCES movie(id_movie) 
        ON DELETE CASCADE,
        
  CONSTRAINT fk_bridge_movie_award_award
        FOREIGN KEY (id_award) 
        REFERENCES award (id_award) 
        ON DELETE CASCADE
);
-- Index on id_movie
CREATE INDEX idx_bridge_movie_award_movie
ON bridge_movie_award (id_movie);

-- Index on id_award
CREATE INDEX idx_bridge_movie_award_award
ON bridge_movie_award (id_award);

-- 14 - create bridge_director_movie tbl
CREATE TABLE bridge_movie_director (
  id_movie INTEGER NOT NULL,
  id_director INTEGER NOT NULL,
  
  -- Desalese the Composite Primary Key (prevents duplicate pairs)
  PRIMARY KEY (id_movie, id_director),
    
  -- Desalese Foreign Key Constraints with Cascade Delete, preventing orphaned data records.
  CONSTRAINT fk_bridge_movie_director_movie 
        FOREIGN KEY (id_movie) 
        REFERENCES movie(id_movie) 
        ON DELETE CASCADE,
        
  CONSTRAINT fk_bridge_movie_director_director
        FOREIGN KEY (id_director)
        REFERENCES director(id_director) 
        ON DELETE CASCADE
);
-- Index on id_movie
CREATE INDEX idx_bridge_movie_director_movie
ON bridge_movie_director (id_movie);

-- Index on id_director
CREATE INDEX idx_bridge_movie_director_director
ON bridge_movie_director (id_director);

-- 15 - create bridge_movie_genre tbl
CREATE TABLE bridge_movie_genre (
  id_movie INTEGER NOT NULL,
  id_genre INTEGER NOT NULL,
  
  -- Desalese the Composite Primary Key (prevents duplicate pairs)
  PRIMARY KEY (id_movie, id_genre),
    
  -- Desalese Foreign Key Constraints with Cascade Delete, preventing orphaned data records.
  CONSTRAINT fk_bridge_movie_genre_movie
        FOREIGN KEY (id_movie) 
        REFERENCES movie(id_movie) 
        ON DELETE CASCADE,
        
  CONSTRAINT fk_bridge_movie_genre_genre 
        FOREIGN KEY (id_genre) 
        REFERENCES genre(id_genre) 
        ON DELETE CASCADE
);
-- Index on id_movie
CREATE INDEX idx_bridge_movie_genre_movie
ON bridge_movie_genre (id_movie);

-- Index on id_genre
CREATE INDEX idx_bridge_movie_genre_genre
ON bridge_movie_genre (id_genre);

-- 16 - create bridge_movie_character tbl
CREATE TABLE bridge_movie_character (
  id_movie INTEGER NOT NULL,
  id_character INTEGER NOT NULL,
  
  -- Desalese the Composite Primary Key (prevents duplicate pairs)
  PRIMARY KEY (id_movie, id_character),
    
  -- Desalese Foreign Key Constraints with Cascade Delete, preventing orphaned data records.
  CONSTRAINT fk_bridge_movie_character_movie
        FOREIGN KEY (id_movie) 
        REFERENCES movie(id_movie) 
        ON DELETE CASCADE,
        
  CONSTRAINT fk_bridge_movie_character_character
        FOREIGN KEY (id_character) 
        REFERENCES character (id_character) 
        ON DELETE CASCADE
);
-- Index on id_movie
CREATE INDEX idx_bridge_movie_character_movie
ON bridge_movie_character (id_movie);

-- Index on id_character
CREATE INDEX idx_bridge_movie_character_character
ON bridge_movie_character(id_character);

-- 17 - create bridge_movie_expert_review tbl
CREATE TABLE bridge_movie_expert_review (
  id_movie INTEGER NOT NULL,
  id_expert_review INTEGER NOT NULL,
  
  -- Desalese the Composite Primary Key (prevents duplicate pairs)
  PRIMARY KEY (id_movie, id_expert_review),
    
  -- Desalese Foreign Key Constraints with Cascade Delete, preventing orphaned data records.
  CONSTRAINT fk_bridge_movie_expert_review_movie 
        FOREIGN KEY (id_movie) 
        REFERENCES movie(id_movie) 
        ON DELETE CASCADE,
        
  CONSTRAINT fk_bridge_movie_expert_review_expert_review
        FOREIGN KEY (id_expert_review) 
        REFERENCES expert_review (id_expert_review) 
        ON DELETE CASCADE
);
-- Index on id_movie
CREATE INDEX idx_bridge_movie_expert_review_movie
ON bridge_movie_expert_review (id_movie);

-- Index on id_expert_review
CREATE INDEX idx_bridge_movie_expert_review_expert_review
ON bridge_movie_expert_review(id_expert_review);

-- 18 - create bridge_movie_user_review tbl
CREATE TABLE bridge_movie_user_review (
  id_movie INTEGER NOT NULL,
  id_user_review INTEGER NOT NULL,
  
  -- Desalese the Composite Primary Key (prevents duplicate pairs)
  PRIMARY KEY (id_movie, id_user_review),
    
  -- Desalese Foreign Key Constraints with Cascade Delete, preventing orphaned data records.
  CONSTRAINT fk_bridge_movie_user_review_movie
        FOREIGN KEY (id_movie) 
        REFERENCES movie(id_movie) 
        ON DELETE CASCADE,
        
  CONSTRAINT fk_bridge_movie_user_review_user_review
        FOREIGN KEY (id_user_review) 
        REFERENCES user_review (id_user_review) 
        ON DELETE CASCADE
);
-- Index on id_movie
CREATE INDEX idx_bridge_movie_user_review_movie
ON bridge_movie_user_review (id_movie);

-- Index on id_user_review
CREATE INDEX idx_bridge_movie_user_review_user_review
ON bridge_movie_user_review(id_user_review);


-- 19 - create bridge_movie_studio tbl
CREATE TABLE bridge_movie_studio (
  id_movie INTEGER NOT NULL,
  id_studio INTEGER NOT NULL,
  
  -- Desalese the Composite Primary Key (prevents duplicate pairs)
  PRIMARY KEY (id_movie, id_studio),
    
  -- Desalese Foreign Key Constraints with Cascade Delete, preventing orphaned data records.
  CONSTRAINT fk_bridge_movie_studio_movie
        FOREIGN KEY (id_movie) 
        REFERENCES movie(id_movie) 
        ON DELETE CASCADE,
        
  CONSTRAINT fk_bridge_movie_studio_studio
        FOREIGN KEY (id_studio) 
        REFERENCES studio (id_studio) 
        ON DELETE CASCADE
);
-- Index on id_movie
CREATE INDEX idx_bridge_movie_studio_movie
ON bridge_movie_studio(id_movie);

-- Index on id_studio
CREATE INDEX idx_bridge_movie_studio_studio
ON bridge_movie_studio(id_studio);

-- 20 - create bridge_movie_keyword tbl
CREATE TABLE bridge_movie_keyword (
  id_movie INTEGER NOT NULL,
  id_keyword INTEGER NOT NULL,
  
  -- Desalese the Composite Primary Key (prevents duplicate pairs)
  PRIMARY KEY (id_movie, id_keyword),
    
  -- Desalese Foreign Key Constraints with Cascade Delete, preventing orphaned data records.
  CONSTRAINT fk_bridge_movie_keyword_movie
        FOREIGN KEY (id_movie) 
        REFERENCES movie(id_movie) 
        ON DELETE CASCADE,
        
  CONSTRAINT fk_bridge_movie_keyword_keyword
        FOREIGN KEY (id_keyword) 
        REFERENCES keyword(id_keyword) 
        ON DELETE CASCADE
);
-- Index on id_movie
CREATE INDEX idx_bridge_movie_keyword_movie
ON bridge_movie_keyword(id_movie);

-- Index on id_keyword
CREATE INDEX idx_bridge_movie_keyword_keyword
ON bridge_movie_keyword(id_keyword);



-- 27 characters VARCHAR(50)
-- 60 characters VARCHAR(100)
-- 44 charactersVARCHAR(100)
-- ~90+ charactersVARCHAR(255)


--select * from movie;
--select * from award;
--select * from genre;
--select * from sales;
--select * from liwc_score;

--select * 
--from movie m
--FULL OUTER JOIN award a ON 1=0 -- 1=0 condition is just to don't join rows
--FULL OUTER JOIN genre g ON 1=0
--FULL OUTER JOIN sales f ON 1=0;

